# GlassAlpha Production Configuration
# For regulatory-ready audits with full compliance
# Documentation: https://glassalpha.com/guides/production/

audit_profile: tabular_compliance

# Data: Production data with explicit schema
data:
  path: data/production_data.csv # REQUIRED: Path to your data
  schema_path: data/schema.yaml # REQUIRED: Data schema definition
  target_column: target # REQUIRED: Your target column
  protected_attributes: # REQUIRED: Protected attributes
    - age_group
    - gender
  feature_columns: [] # REQUIRED: List all features explicitly

# Model: Production model with preprocessing
model:
  path: models/production_model.pkl # REQUIRED: Path to trained model
  type: xgboost # Your model type

# Preprocessing: REQUIRED for production
preprocessing:
  mode: artifact # REQUIRED: Use verified artifact
  artifact_path: models/preprocessor.joblib
  expected_file_hash: "" # REQUIRED: Run 'glassalpha prep hash' first
  expected_params_hash: "" # REQUIRED: Run 'glassalpha prep hash' first
  class_allowlist: # REQUIRED: Approved transformers
    - sklearn.preprocessing.StandardScaler
    - sklearn.preprocessing.OneHotEncoder

# Explainers: Comprehensive analysis
explainers:
  strategy: first_compatible
  priority:
    - treeshap # Primary for tree models
    - coefficients # Primary for linear models
    - permutation # Universal fallback
  config:
    treeshap:
      max_samples: 1000
      check_additivity: true
    permutation:
      n_repeats: 10
      random_state: 42

# Metrics: Complete compliance analysis
metrics:
  performance:
    - accuracy
    - precision_weighted
    - recall_weighted
    - f1_weighted
    - roc_auc
  fairness:
    - demographic_parity
    - equal_opportunity
    - equalized_odds
    - predictive_parity
  drift:
    - psi
    - kl_divergence
    - ks_statistic

# Recourse: Enable actionable recommendations
recourse:
  enabled: true
  immutable_features:
    - age_group
    - gender
  cost_config:
    feature_costs: {}
    default_cost: 1.0

# Reproducibility: Full determinism
reproducibility:
  random_seed: 42
  deterministic: true
  capture_environment: true

# Report: PDF for regulatory submission
report:
  output_format: pdf
  title: "Production Audit Report"
  include_data_summary: true
  include_model_details: true

# Manifest: Full audit trail
manifest:
  enabled: true
  include_git_sha: true
  include_config_hash: true
  include_data_hash: true
  include_model_hash: true

# Strict mode: REQUIRED for production
strict_mode: true
