repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1 # Use latest version
    hooks:
      - id: ruff
        args: [--fix, --exit-zero] # Auto-fix and succeed (don't block on lint errors)
        exclude: ^dev/.*\.py$
      - id: ruff-format # Auto-format (no args = format, not check)
        exclude: ^dev/.*\.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [--fix=lf] # Ensure LF line endings
      - id: check-added-large-files # Catch AI dumping large files
        args: [--maxkb=500]
      - id: check-case-conflict # Catch case-sensitive filename issues

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types: [yaml]
        exclude: ^site/mkdocs\.yml$

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [--strict]
        exclude: ^site/mkdocs\.yml$

  - repo: local
    hooks:
      - id: check-package-structure
        name: Verify package structure
        entry: python3 scripts/check_package_structure.py
        language: system
        pass_filenames: false
      - id: smoke-test
        name: Quick smoke test
        entry: bash scripts/smoke_test.sh
        language: system
        pass_filenames: false
        stages: [push]
# MyPy disabled during architectural foundation phase
# Will re-enable when Phase 1 implementation is complete
# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v1.18.2
#   hooks:
#     - id: mypy
#       additional_dependencies: [types-PyYAML]
#       args: [--strict]
