repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1 # Use latest version
    hooks:
      - id: ruff
        args: [--fix, --unsafe-fixes] # Max auto-fix for solo development
        exclude: ^(dev/demo_.*\.py|dev/.*_review\.py|tests/test_.*\.py)$
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-toml
      - id: check-json
      - id: mixed-line-ending
        args: [--fix=lf] # Ensure LF line endings

  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.49"
    hooks:
      - id: check-manifest
        args: [--verbose]
        # Requires setup.py or pyproject.toml packaging context
        additional_dependencies: [build, setuptools, wheel]
# MyPy disabled during architectural foundation phase
# Will re-enable when Phase 1 implementation is complete
# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v1.18.2
#   hooks:
#     - id: mypy
#       additional_dependencies: [types-PyYAML]
#       args: [--strict]
