audit_profile: tabular_compliance

reproducibility:
  random_seed: 42

data:
  dataset: custom
  path: custom_data.csv
  target_column: default
  feature_columns:
    - age
    - income
    - education
    - loan_amount

model:
  type: lightgbm
  params:
    random_state: 42
    n_estimators: 10
    max_depth: 2

explainers:
  strategy: first_compatible
  priority:
    - treeshap

report:
  output_format: html
