# GlassAlpha Development Configuration
# For iterative model development and testing
# Documentation: https://glassalpha.com/guides/development/

audit_profile: tabular_compliance

# Data: Flexible for development
data:
  dataset: german_credit # Can use built-in or custom data
  # path: data/dev_data.csv        # Uncomment for custom data
  target_column: credit_risk
  protected_attributes:
    - age_group

# Model: Train from config for quick iteration
model:
  type: xgboost
  save_path: models/dev_model.pkl # Auto-save for reasons/recourse commands
  params:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    random_state: 42

# Preprocessing: Auto mode for development (NOT for production)
preprocessing:
  mode: auto # Automatic preprocessing for speed

# Explainers: Balance speed and insight
explainers:
  strategy: first_compatible
  priority:
    - treeshap
    - permutation
  config:
    treeshap:
      max_samples: 500 # Faster with fewer samples
    permutation:
      n_repeats: 5 # Quick iteration

# Metrics: Development focus
metrics:
  performance:
    - accuracy
    - f1_weighted
    - roc_auc
  fairness:
    - demographic_parity
    - equal_opportunity

# Reproducibility: Balanced
reproducibility:
  random_seed: 42
  deterministic: true
  capture_environment: false # Skip for speed

# Report: HTML for quick feedback
report:
  output_format: html
  title: "Development Audit Report"

# Manifest: Enabled for tracking
manifest:
  enabled: true
  include_git_sha: true

# Strict mode: Disabled for flexibility
strict_mode: false
