authors:
  Gabriel Mays:
    name: Gabe Mays
    description: Founder
    avatar: https://secure.gravatar.com/avatar/4bd19f03fd2f5ea1fd10e6b2091a680aa7f9e56830759ddfab86f2d5bcfcf537?s=200&d=blank&r=g
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/gmays
