site_name: Glass Alpha
site_description: Open-source AI compliance toolkit.
site_url: https://glassalpha.com
repo_url: https://github.com/GlassAlpha/glassalpha
repo_name: GlassAlpha/glassalpha
edit_uri: edit/main/site/docs/

theme:
  name: material
  # custom_dir: overrides  # Uncomment when overrides directory exists
  # logo: assets/logo.png  # Uncomment when logo exists
  # favicon: assets/favicon.png  # Uncomment when favicon exists
  palette:
    - scheme: default
      primary: slate   # deep navy/gray
      accent: cyan     # subtle tech/AI vibe
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: slate
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

plugins:
  - search
#  - mkdocstrings: # Off until we have actual Python modules and need this
#      handlers:
#        python:
#          paths: [../packages/src]
#          options:
#            docstring_style: google
#            show_source: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      timezone: UTC
  - minify:
      minify_html: true
  - blog:
      archive: false
  - open-in-new-tab:
      add_icon: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.magiclink:
      repo_url_shorthand: true
      social_url_shorthand: true
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Hello Audit Tutorial: getting-started/quickstart.md
  - Reference:
    - Phase 1 Scope & Limitations: limitations.md
    - Contributing: contributing.md
  - Blog: 
    - blog/index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GlassAlpha/glassalpha
#  analytics:
#    provider: google
#    property: !ENV GOOGLE_ANALYTICS_KEY

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
