site_name: Glass Alpha
site_description: Open-source AI compliance toolkit.
site_url: https://glassalpha.com
repo_url: https://github.com/GlassAlpha/glassalpha
repo_name: GlassAlpha/glassalpha
edit_uri: edit/main/site/docs/

theme:
  name: material
  # custom_dir: overrides  # Uncomment when overrides directory exists
  # logo: assets/logo.png  # Uncomment when logo exists
  # favicon: assets/favicon.png  # Uncomment when favicon exists
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [../packages/src]
          options:
            docstring_style: google
            show_source: true
  # - git-revision-date-localized:
  #     enable_creation_date: true
  - minify:
      minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Examples: getting-started/examples.md
  - Features:
    - Explainability: features/explainability.md
    - Counterfactuals: features/counterfactuals.md
    - Audit Reports: features/audit.md
    - Fairness: features/fairness.md
    - Drift Monitoring: features/drift.md
  - API Reference:
    - Overview: api/overview.md
    - Explainability: api/explainability.md
    - Counterfactuals: api/counterfactuals.md
    - Audit: api/audit.md
  - Examples:
    - German Credit: examples/german-credit.md
    - COMPAS Bias: examples/compas.md
    - Adult Income: examples/adult-income.md
  - Contributing: contributing.md
  - Assumptions & Limitations: limitations.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GlassAlpha/glassalpha
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
