# ==============================================================================
# Adult Income (Census) Dataset Audit Configuration
# ==============================================================================
#
# Dataset: Adult Census Income
# Source: UCI Machine Learning Repository
# Size: 48,842 samples, 14 features
# Task: Predict whether income exceeds $50K/year
# Protected Attributes: Race, sex, age, native-country
#
# This is one of the most-studied fairness benchmarks in ML. The dataset contains
# census data and is known to have biases related to gender and race.
#
# Download Instructions:
# 1. Training data: https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data
# 2. Test data: https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test
# 3. Save as: ~/data/adult_income.csv
#
# Data Preparation:
# - Add column headers (see feature_columns below)
# - Combine train and test sets or use separately
# - Handle missing values (marked as '?')
#
# Expected Findings:
# - Gender bias: Males typically have higher predicted income
# - Race disparities: White individuals often favored
# - Age effects: Older workers have higher incomes
#
# Documentation: https://glassalpha.com/getting-started/data-sources/#adult-income-census
# ==============================================================================

audit_profile: tabular_compliance

# Reproducibility settings
reproducibility:
  random_seed: 42
  deterministic: true
  capture_environment: true

# Data configuration
data:
  dataset: custom
  path: ~/data/adult_income.csv # Update this path to your data location
  target_column: income # Binary: '>50K' or '<=50K'

  # All features in the Adult dataset
  feature_columns:
    - age
    - workclass
    - fnlwgt # Final weight (census weighting)
    - education
    - education_num # Years of education
    - marital_status
    - occupation
    - relationship
    - race
    - sex
    - capital_gain
    - capital_loss
    - hours_per_week
    - native_country

  # Protected attributes for fairness analysis
  protected_attributes:
    - sex # Primary protected attribute
    - race # Secondary protected attribute
    - age # Can be used for age discrimination analysis
    - native_country # National origin discrimination

# Model configuration
model:
  type: xgboost # Recommended for this dataset
  # Note: XGBoost requires: pip install 'glassalpha[explain]'
  # Will use logistic_regression if XGBoost not available

  params:
    objective: binary:logistic
    eval_metric: logloss
    n_estimators: 150 # More trees for better accuracy
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42

# Explainer configuration
explainers:
  strategy: first_compatible
  priority:
    - treeshap # Best for XGBoost
    - permutation # Fallback if SHAP not installed

  config:
    treeshap:
      max_samples: 1000 # Sample for speed
      check_additivity: true

    permutation:
      n_repeats: 10
      random_state: 42

# Metrics configuration
metrics:
  performance:
    metrics:
      - accuracy
      - precision
      - recall
      - f1
      - auc_roc
      - classification_report

  fairness:
    metrics:
      - demographic_parity
      - equal_opportunity
      - equalized_odds
      - predictive_parity

    config:
      # Standard thresholds for employment/income
      demographic_parity:
        threshold: 0.05 # 5% maximum difference
      equal_opportunity:
        threshold: 0.05
      equalized_odds:
        threshold: 0.05

# Preprocessing configuration
# Note: Preprocessing options are coming in a future release
# GlassAlpha currently handles preprocessing automatically

# Report configuration
report:
  template: standard_audit
  output_format: pdf
  styling:
    color_scheme: professional
    compliance_statement: true

  include_sections:
    - executive_summary
    - data_overview
    - model_performance
    - global_explanations
    - fairness_analysis
    - audit_manifest
# Manifest configuration
# Note: Manifest is automatically generated with each audit
# Custom manifest options are coming in a future release
# ==============================================================================
# Usage:
#   glassalpha audit --config adult_income.yaml --output adult_income_audit.pdf --strict
#
# Expected Results:
# - Accuracy: ~85% (typical for this dataset)
# - Gender bias: Likely detected (males favored)
# - Race bias: Likely detected (disparities across races)
#
# Troubleshooting:
# - If file not found: Update data.path to your actual file location
# - If XGBoost missing: Will auto-fallback to LogisticRegression
# - If SHAP missing: Will auto-fallback to Permutation importance
#
# Next Steps:
# - Try different models (lightgbm, logistic_regression)
# - Adjust fairness thresholds for your requirements
# - Compare with other datasets: https://glassalpha.com/getting-started/data-sources/
# ==============================================================================
