# CCPA Compliance Audit Configuration
# Example configuration for auditing automated decision-making systems
# Focuses on California Consumer Privacy Act compliance and consumer rights

audit_profile: ccpa_compliance

# Reproducibility for regulatory compliance
reproducibility:
  random_seed: 42

# Dataset configuration
data:
  path: /Users/gabe/.glassalpha/data/ccpa_compliance.csv
  target_column: automated_decision_consent
  protected_attributes:
    - age
    - california_resident

# XGBoost model for automated decision consent prediction
model:
  type: xgboost
  params:
    objective: binary:logistic
    eval_metric: logloss
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42

# Explanation configuration
explainers:
  strategy: first_compatible
  priority:
    - treeshap    # XGBoost supports TreeSHAP for CCPA transparency
    - kernelshap  # Fallback for any model type
  config:
    treeshap:
      max_samples: 1000
      check_additivity: true

# CCPA-specific metrics
metrics:
  performance:
    metrics:
      - accuracy
      - precision    # Important for consent accuracy
      - recall       # Important for consumer rights
      - f1
      - auc_roc     # Overall discriminative ability

  fairness:
    metrics:
      - demographic_parity    # Equal consent rates across groups
      - equal_opportunity     # Equal TPR for consent prediction
      - predictive_parity      # Equal precision across demographic groups
    config:
      # CCPA-compliant thresholds
      demographic_parity:
        threshold: 0.05  # Maximum 5% difference
      equal_opportunity:
        threshold: 0.05
      predictive_parity:
        threshold: 0.05

# Professional CCPA audit report
report:
  template: standard_audit
