# Customer Segmentation Audit Configuration
# Example configuration for auditing multi-class customer segmentation models
# Focuses on marketing compliance and consumer privacy regulations

audit_profile: customer_segmentation

# Reproducibility for regulatory compliance
reproducibility:
  random_seed: 42

# Dataset configuration
data:
  path: ~/.glassalpha/data/customer_segmentation.csv
  target_column: customer_segment
  protected_attributes:
    - gender
    - age_group

# Random Forest model for multi-class segmentation
model:
  type: sklearn_generic
  params:
    model_type: RandomForestClassifier
    n_estimators: 100
    max_depth: 10
    random_state: 42

# Explanation configuration (Random Forest needs KernelSHAP)
explainers:
  strategy: first_compatible
  priority:
    - kernelshap  # Random Forest requires model-agnostic explanations
  config:
    kernelshap:
      n_samples: 1000
      background_size: 100

# Multi-class specific metrics
metrics:
  performance:
    metrics:
      - accuracy
      - precision_macro    # Average precision across all segments
      - recall_macro       # Average recall across all segments
      - f1_macro          # Macro-averaged F1 score

  fairness:
    metrics:
      - demographic_parity    # Equal representation in each segment
      - equal_opportunity     # Equal classification accuracy across groups
    config:
      demographic_parity:
        threshold: 0.05  # Maximum 5% difference in segment distribution
      equal_opportunity:
        threshold: 0.05

# Professional audit report
report:
  template: standard_audit
  styling:
    color_scheme: professional
    compliance_statement: true
