# Folktables ACS Income Prediction Configuration
# Dataset: American Community Survey (ACS) Public Use Microdata Sample
# Task: Predict whether an individual's income exceeds $50,000
# Protected Attributes: SEX, RAC1P (race), AGEP (age)
# Size: ~1.6M individuals (can be filtered by state/year)
# Source: https://github.com/socialfoundations/folktables
#
# Note: Folktables requires additional setup:
# 1. Install: pip install folktables
# 2. Download data using folktables API
# 3. Export to CSV for use with GlassAlpha
#
# This config assumes you've exported the data to CSV format.

audit_profile: tabular_compliance

reproducibility:
  random_seed: 42
  config_hash: auto
  git_commit: auto

data:
  source: /path/to/folktables_income.csv
  target_column: income_binary # 1 if income >$50K, 0 otherwise
  protected_attributes:
    - SEX # 1=Male, 2=Female
    - RAC1P # Race (1=White, 2=Black, 3-9=Other)
    - AGEP # Age in years
  feature_columns: auto # Or specify: [AGEP, COW, SCHL, MAR, OCCP, POBP, RELP, WKHP, SEX, RAC1P]

  # Folktables-specific notes:
  # - ACS data is very large; consider filtering by state
  # - Missing values are coded as specific values (see Folktables docs)
  # - Some features are categorical and need encoding

model:
  type: xgboost
  params:
    objective: binary:logistic
    n_estimators: 200
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
    # Large dataset optimization:
    tree_method: hist # Faster for large data
    max_bin: 256 # Balance speed/accuracy

explainers:
  shap:
    enabled: true
    max_samples: 1000 # Limit for large dataset
    check_additivity: false # Faster for large models

  # For very large models, consider:
  # max_samples: 500
  # background_samples: 100

metrics:
  performance:
    - accuracy
    - precision
    - recall
    - f1
    - roc_auc

  fairness:
    - demographic_parity
    - equal_opportunity
    - equalized_odds
    - predictive_parity

  # Important for Folktables:
  # - Check fairness across SEX
  # - Check fairness across RAC1P groups
  # - Age (AGEP) can reveal age discrimination

report:
  title: "Folktables ACS Income Prediction Audit"
  description: |
    Fairness audit of income prediction model using American Community Survey data.
    This dataset is commonly used for fairness research and benchmarking.

  output_path: folktables_audit.pdf

  template: default

  sections:
    - overview
    - performance
    - explanations
    - fairness
    - recommendations
# Folktables-specific considerations:
# 1. Large dataset size: Consider sampling or filtering by state
# 2. Missing values: Folktables codes missing as specific values (e.g., 0)
# 3. Categorical features: May need encoding before use
# 4. Multiple protected attributes: Check intersectional fairness
# 5. Geographic variation: Results may vary by state/region
#
# Example preprocessing:
# - Filter to single state: df[df['ST'] == 6]  # California
# - Filter to recent year: Use 2018 or later
# - Handle missing values: Replace coded values with NaN
# - Encode categoricals: Use scikit-learn's OrdinalEncoder
#
# For more information:
# - Folktables paper: https://arxiv.org/abs/2108.04884
# - GitHub: https://github.com/socialfoundations/folktables
# - ACS documentation: https://www.census.gov/programs-surveys/acs/
