# Financial Fraud Detection Audit Configuration
# Example configuration for auditing credit card fraud detection models
# Focuses on payment card industry compliance and anti-money laundering

audit_profile: fraud_detection

# Reproducibility for regulatory compliance
reproducibility:
  random_seed: 42

# Dataset configuration
data:
  path: ~/.glassalpha/data/fraud_detection.csv
  target_column: is_fraud
  protected_attributes:
    - cardholder_age
    - card_type

# XGBoost model optimized for fraud detection
model:
  type: xgboost
  params:
    objective: binary:logistic
    eval_metric: logloss
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    scale_pos_weight: 99  # Handle 1% fraud rate
    random_state: 42

# Explanation configuration
explainers:
  strategy: first_compatible
  priority:
    - treeshap    # XGBoost supports TreeSHAP for exact explanations
    - kernelshap  # Fallback for any model type
  config:
    treeshap:
      max_samples: 1000
      check_additivity: true

# Fraud-specific metrics
metrics:
  performance:
    metrics:
      - accuracy
      - precision    # Critical for fraud - minimize false positives
      - recall       # Critical for fraud - catch actual fraud
      - f1          # Balance between precision and recall
      - auc_roc     # Overall discriminative ability

  fairness:
    metrics:
      - demographic_parity    # Equal fraud detection rates across groups
      - equal_opportunity     # Equal true positive rates for fraud detection
      - predictive_parity      # Equal precision across demographic groups
    config:
      # Stricter thresholds for fraud detection
      demographic_parity:
        threshold: 0.02  # Maximum 2% difference
      equal_opportunity:
        threshold: 0.02
      predictive_parity:
        threshold: 0.02

# Professional audit report
report:
  template: standard_audit
