# GDPR Compliance Audit Configuration
# Example configuration for auditing automated decision-making systems
# Focuses on EU GDPR Article 22 compliance and data protection impact assessments
#
# 🔧 ADAPT THIS: Replace with your own data and model for GDPR compliance auditing
# See: https://glassalpha.org/getting-started/custom-data/

audit_profile: tabular_compliance

# Reproducibility for regulatory compliance
reproducibility:
  random_seed: 42 # 🔧 ADAPT THIS: Use a different seed if needed

# Dataset configuration
data:
  dataset: custom # Use custom dataset with path
  # 🔧 ADAPT THIS: Replace with your dataset path
  path: ~/.glassalpha/data/german_credit_processed.csv

  # 🔧 ADAPT THIS: Update to match your target column name
  target_column: credit_risk

  # 🔧 ADAPT THIS: Specify your feature columns or use "auto"
  feature_columns:
    - checking_account_status
    - duration_months
    - credit_amount
    - savings_account
    - employment_duration
    - age_years
    - gender

  # 🔧 ADAPT THIS: List your protected attributes for fairness analysis
  # Common GDPR protected attributes: gender, age, nationality, ethnicity
  protected_attributes:
    - gender
    - age_years

# LightGBM model for consent prediction
model:
  # 🔧 ADAPT THIS: Choose your model type (logistic_regression, xgboost, lightgbm)
  # See: https://glassalpha.org/reference/model-selection/
  type: lightgbm

  # 🔧 ADAPT THIS: Tune model parameters for your specific use case
  params:
    objective: binary
    metric: binary_logloss
    n_estimators: 100 # 🔧 ADAPT THIS: Increase for better accuracy (100-300 typical)
    max_depth: 6 # 🔧 ADAPT THIS: Control model complexity (3-10)
    learning_rate: 0.1 # 🔧 ADAPT THIS: Lower for more accurate models (0.01-0.3)
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42

# Explanation configuration
explainers:
  strategy: first_compatible
  priority:
    - treeshap # LightGBM supports TreeSHAP for GDPR transparency
    - kernelshap # Fallback for any model type
  config:
    treeshap:
      max_samples: 1000
      check_additivity: true

# GDPR-specific metrics
metrics:
  performance:
    metrics:
      - accuracy
      - precision # Important for consent accuracy
      - recall # Important for consent completeness
      - f1
      - auc_roc # Overall discriminative ability

  fairness:
    metrics:
      - demographic_parity # Equal consent rates across groups
      - equal_opportunity # Equal TPR for consent prediction
      - predictive_parity # Equal precision across demographic groups
    config:
      # 🔧 ADAPT THIS: Adjust fairness thresholds based on your risk tolerance
      # GDPR typically requires stricter thresholds (0.01-0.05)
      # Healthcare/Finance: Use 0.01-0.03 for high-stakes decisions
      # General business: 0.05-0.10 may be acceptable
      demographic_parity:
        threshold: 0.05 # Maximum 5% difference
      equal_opportunity:
        threshold: 0.05
      predictive_parity:
        threshold: 0.05

# Professional GDPR audit report
report:
  template: standard_audit
