# GDPR Compliance Audit Configuration
# Example configuration for auditing automated decision-making systems
# Focuses on EU GDPR Article 22 compliance and data protection impact assessments

audit_profile: tabular_compliance

# Reproducibility for regulatory compliance
reproducibility:
  random_seed: 42

# Dataset configuration
data:
  path: ~/.glassalpha/data/german_credit_processed.csv
  target_column: credit_risk
  feature_columns:
    - checking_account_status
    - duration_months
    - credit_amount
    - savings_account
    - employment_duration
    - age_years
    - gender
  protected_attributes:
    - gender
    - age_years

# LightGBM model for consent prediction
model:
  type: lightgbm
  params:
    objective: binary
    metric: binary_logloss
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42

# Explanation configuration
explainers:
  strategy: first_compatible
  priority:
    - treeshap    # LightGBM supports TreeSHAP for GDPR transparency
    - kernelshap  # Fallback for any model type
  config:
    treeshap:
      max_samples: 1000
      check_additivity: true

# GDPR-specific metrics
metrics:
  performance:
    metrics:
      - accuracy
      - precision    # Important for consent accuracy
      - recall       # Important for consent completeness
      - f1
      - auc_roc     # Overall discriminative ability

  fairness:
    metrics:
      - demographic_parity    # Equal consent rates across groups
      - equal_opportunity     # Equal TPR for consent prediction
      - predictive_parity      # Equal precision across demographic groups
    config:
      # GDPR-compliant thresholds
      demographic_parity:
        threshold: 0.05  # Maximum 5% difference
      equal_opportunity:
        threshold: 0.05
      predictive_parity:
        threshold: 0.05

# Professional GDPR audit report
report:
  template: standard_audit
