# GlassAlpha Example: German Credit (Simplified)
# Usage: glassalpha audit --config german_credit_simple.yaml --output german_credit_simple_audit.html
# Built-in dataset: german_credit (automatically fetched)
#
# This is a RUNNABLE EXAMPLE with basic metrics only.
# For full audit: use german_credit.yaml

audit_profile: tabular_compliance

reproducibility:
  random_seed: 42

data:
  dataset: german_credit
  fetch: if_missing
  offline: false
  target_column: credit_risk
  feature_columns:
    - checking_account_status
    - duration_months
    - credit_amount
    - savings_account
    - employment_duration
    - age_years
    - gender
  protected_attributes:
    - gender

model:
  type: logistic_regression
  params:
    random_state: 42
    max_iter: 1000

explainers:
  strategy: first_compatible
  priority:
    - coefficients # Zero-dependency explainer for linear models
  config:
    coefficients:
      normalize: true

metrics:
  performance:
    metrics:
      - accuracy
      - precision
      - recall
  fairness:
    metrics:
      - demographic_parity
      - equal_opportunity

report:
  template: standard_audit
  output_format: html
