audit_profile: tabular_compliance

reproducibility:
  random_seed: 42

data:
  path: ~/.glassalpha/data/german_credit_processed.csv
  target_column: credit_risk
  feature_columns:
    - checking_account_status
    - duration_months
    - credit_amount
    - savings_account
    - employment_duration
    - age_years
    - gender
  protected_attributes:
    - gender

model:
  type: xgboost
  params:
    objective: binary:logistic
    eval_metric: logloss
    n_estimators: 50
    learning_rate: 0.1
    max_depth: 3

explainers:
  strategy: first_compatible
  priority:
    - treeshap
  config:
    treeshap:
      max_samples: 100

metrics:
  performance:
    metrics:
      - accuracy
      - precision
      - recall
  fairness:
    metrics:
      - demographic_parity
      - equal_opportunity

report:
  template: standard_audit
  output_format: pdf
