audit_profile: tabular_compliance

reproducibility:
  random_seed: 42

data:
  dataset: german_credit
  fetch: if_missing
  offline: false
  target_column: credit_risk
  feature_columns:
    - checking_account_status
    - duration_months
    - credit_amount
    - savings_account
    - employment_duration
    - age_years
    - gender
  protected_attributes:
    - gender

model:
  type: logistic_regression
  params:
    random_state: 42
    max_iter: 1000

explainers:
  strategy: first_compatible
  priority:
    - treeshap
  config:
    treeshap:
      max_samples: 100

metrics:
  performance:
    metrics:
      - accuracy
      - precision
      - recall
  fairness:
    metrics:
      - demographic_parity
      - equal_opportunity

report:
  template: standard_audit
  output_format: html
