# Healthcare Treatment Outcomes Audit Configuration
# Example configuration for auditing clinical decision support models
# Focuses on FDA regulation and clinical trial compliance

audit_profile: healthcare_outcomes

# Reproducibility for regulatory compliance
reproducibility:
  random_seed: 42

# Dataset configuration
data:
  path: ~/.glassalpha/data/healthcare_outcomes.csv
  target_column: treatment_outcome
  protected_attributes:
    - gender
    - age_group
    - race_ethnicity

# XGBoost model optimized for clinical outcomes
model:
  type: xgboost
  params:
    objective: binary:logistic
    eval_metric: logloss
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42

# Explanation configuration
explainers:
  strategy: first_compatible
  priority:
    - treeshap    # XGBoost supports TreeSHAP for clinical interpretability
    - kernelshap  # Fallback for any model type
  config:
    treeshap:
      max_samples: 1000
      check_additivity: true

# Clinical and fairness metrics
metrics:
  performance:
    metrics:
      - accuracy
      - precision    # Critical for clinical decisions - avoid false positives
      - recall       # Critical for clinical decisions - catch treatment failures
      - f1          # Balance between precision and recall
      - auc_roc     # Overall discriminative ability

  fairness:
    metrics:
      - demographic_parity    # Equal treatment outcomes across groups
      - equal_opportunity     # Equal true positive rates for treatment success
      - equalized_odds        # Equal TPR and FPR across demographic groups
    config:
      # Stricter thresholds for healthcare
      demographic_parity:
        threshold: 0.03  # Maximum 3% difference
      equal_opportunity:
        threshold: 0.03
      equalized_odds:
        threshold: 0.03

# Professional clinical audit report
report:
  template: standard_audit
  styling:
    color_scheme: professional
    compliance_statement: true
