# Insurance Risk Assessment Audit Configuration
# Example configuration for auditing insurance claim prediction models
# Focuses on regulatory compliance in insurance rate-setting and underwriting

audit_profile: insurance_risk_assessment

# Reproducibility for regulatory compliance
reproducibility:
  random_seed: 42

# Dataset configuration
data:
  path: ~/.glassalpha/data/insurance_risk.csv
  target_column: claim_outcome
  protected_attributes:
    - gender
    - age_group

# LightGBM model optimized for insurance risk assessment
model:
  type: lightgbm
  params:
    objective: binary
    metric: binary_logloss
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42

# Explanation configuration
explainers:
  strategy: first_compatible
  priority:
    - treeshap    # LightGBM supports TreeSHAP for exact explanations
    - kernelshap  # Fallback for any model type
  config:
    treeshap:
      max_samples: 1000
      check_additivity: true

# Comprehensive metrics for insurance compliance
metrics:
  performance:
    metrics:
      - accuracy
      - precision    # Important for false positive analysis
      - recall       # Important for false negative analysis
      - f1
      - auc_roc     # Overall discriminative ability

  fairness:
    metrics:
      - demographic_parity    # Equal approval rates across groups
      - equal_opportunity     # Equal true positive rates
      - equalized_odds        # Equal TPR and FPR across groups
    config:
      # Stricter thresholds for insurance industry
      demographic_parity:
        threshold: 0.05  # Maximum 5% difference
      equal_opportunity:
        threshold: 0.05
      equalized_odds:
        threshold: 0.05

# Professional audit report
report:
  template: standard_audit
  styling:
    color_scheme: professional
    compliance_statement: true
