# GlassAlpha Reason Codes Configuration
# Example: German Credit Dataset
#
# This configuration generates ECOA-compliant adverse action notices
# by extracting top-N negative feature contributions from SHAP values.
#
# Usage:
#   glassalpha reasons \
#     --model artifacts/german_credit_model.pkl \
#     --data artifacts/german_credit_test.csv \
#     --instance 42 \
#     --config configs/reason_codes_german_credit.yaml \
#     --output notices/instance_42.txt

# Audit profile (required)
audit_profile: "tabular_compliance"

# Model configuration
model:
  type: "xgboost"
  path: "artifacts/german_credit_model.pkl"

# Data configuration
data:
  # Dataset identifier or path
  dataset: "german_credit"

  # Protected attributes to exclude from reason codes (ECOA compliance)
  # These will never appear in adverse action notices
  protected_attributes:
    - "age"
    - "foreign_worker"
    - "personal_status_sex" # If using one-hot encoded version

  # Target column (for dropping from features)
  target_column: "target"

  # Feature columns (if needed for validation)
  # feature_columns: [...]

# Explainer configuration
explainers:
  strategy: "first_compatible"
  priority:
    - "treeshap"
    - "kernelshap"
    - "noop"
  config:
    treeshap:
      max_samples: 1000

# Reproducibility
reproducibility:
  # Random seed for deterministic tie-breaking
  random_seed: 42

  # Ensure byte-identical results
  deterministic: true

# Strict mode (optional - enforces all requirements)
strict_mode: false
