# GlassAlpha Configuration: Counterfactual Recourse (German Credit)
#
# This configuration demonstrates recourse generation with policy constraints
# for the German Credit dataset. Generates feasible counterfactual recommendations
# for individuals receiving adverse credit decisions.
#
# Usage:
#   glassalpha recourse \
#     --model models/german_credit.pkl \
#     --data data/test.csv \
#     --instance 42 \
#     --config configs/recourse_german_credit.yaml \
#     --output recourse/instance_42.json

# Audit Profile
audit_profile: tabular_compliance

# Data Configuration
data:
  dataset: german_credit
  fetch: if_missing
  protected_attributes:
    - age
    - gender
    - foreign_worker
  target_column: target

# Model Configuration
model:
  type: xgboost
  path: models/german_credit.pkl

# Recourse Configuration
recourse:
  enabled: true

  # Immutable features (cannot be changed)
  # These represent attributes that individuals cannot reasonably modify
  immutable_features:
    - age # Cannot change age
    - gender # Protected attribute
    - foreign_worker # Immigration status fixed
    - employment_duration # Historical data
    - present_residence_duration # Historical data

  # Monotonic constraints (directional restrictions)
  # Features that can only change in one direction
  monotonic_constraints:
    # Financial improvements (can only increase)
    credit_amount: increase_only # Cannot reduce existing debt obligation
    savings_balance: increase_only # Can save more
    checking_balance: increase_only # Can increase balance

    # Debt reduction (can only decrease)
    num_existing_credits: decrease_only # Can pay off credits
    num_dependents: decrease_only # Unlikely to increase dependents

  # Cost function for optimization
  cost_function: weighted_l1 # Weighted L1 distance

  # Maximum iterations for optimization
  max_iterations: 100

# Reproducibility
reproducibility:
  random_seed: 42
  deterministic: true
# German Credit Feature Semantics
#
# Easily Modifiable (Low Cost):
# - checking_balance: Open new account, transfer funds
# - savings_balance: Deposit savings
# - purpose: Change loan purpose
#
# Moderately Modifiable (Medium Cost):
# - credit_amount: Request different amount
# - duration: Adjust loan duration
# - installment_rate: Negotiate different rate
#
# Difficult to Modify (High Cost):
# - employment_duration: Requires time/job change
# - property: Requires purchasing property
# - other_installment_plans: Complex financial restructuring
#
# Immutable (Cannot Change):
# - age: Cannot change
# - gender: Protected attribute
# - foreign_worker: Immigration status
# - present_residence_duration: Historical data
#
# Policy Rationale:
# This configuration balances feasibility (what individuals can actually change)
# with ECOA compliance (avoiding protected attributes). Monotonic constraints
# ensure recommendations are realistic (e.g., don't suggest increasing debt).
