# German Credit Dataset Audit Configuration (Simplified)
# This configuration demonstrates a complete ML audit pipeline for credit risk assessment
# using the German Credit dataset with fairness and bias analysis.

# =============================================================================
# MODEL CONFIGURATION
# =============================================================================

model:
  # Model type - triggers XGBoostWrapper directly
  type: "xgboost"

  # Additional model parameters (will be used to create a new model)
  params:
    max_depth: 6
    learning_rate: 0.1
    n_estimators: 100
    objective: "binary:logistic"
    eval_metric: "logloss"
    random_state: 42

# =============================================================================
# DATA CONFIGURATION
# =============================================================================

data:
  # Dataset key for built-in datasets
  dataset: "german_credit"

  # Protected attributes for fairness analysis
  protected_attributes:
    - "gender"
    - "age_group"
    - "foreign_worker"

# =============================================================================
# EXPLAINER CONFIGURATION
# =============================================================================

explainers:
  # Strategy for selecting explainers
  strategy: "first_compatible"

  # Priority order - first compatible explainer will be selected
  priority:
    - "treeshap"
    - "coefficients"

  # Explainer-specific configuration
  config:
    treeshap:
      max_samples: 1000
      check_additivity: true

# =============================================================================
# METRICS CONFIGURATION
# =============================================================================

metrics:
  # Performance metrics for model evaluation
  performance:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
    - "auc_roc"

  # Fairness metrics for bias detection
  fairness:
    - "demographic_parity"
    - "equal_opportunity"
    - "equalized_odds"

  # Enable confidence intervals
  compute_confidence_intervals: true
  n_bootstrap: 1000

# =============================================================================
# REPRODUCIBILITY CONFIGURATION
# =============================================================================

reproducibility:
  # Master random seed for all randomness sources
  random_seed: 42

  # Enforce deterministic behavior
  deterministic: true

# =============================================================================
# REPORT CONFIGURATION
# =============================================================================

report:
  # Output format (HTML for examples, PDF for production)
  output_format: "html"

  # Output path for the generated report
  output_path: "audit_report.html"

  # Report sections to include
  include_sections:
    - "executive_summary"
    - "data_overview"
    - "model_performance"
    - "global_explanations"
    - "local_explanations"
    - "fairness_analysis"
    - "audit_manifest"

# =============================================================================
# PREPROCESSING CONFIGURATION
# =============================================================================

preprocessing:
  # Mode for preprocessing
  mode: "auto"
