# CI Template - Robust cross-platform testing with constraint files
# Copy this to .github/workflows/ci.yml when ready to add CI

name: CI - Cross Platform

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14]
        python-version: ["3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            packages/pyproject.toml
            packages/constraints/constraints-${{ runner.os }}-py${{ matrix.python-version }}.txt

      - name: Install OS deps (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          # OpenMP for xgboost at runtime, cairo/pango for HTML→PDF if you add WeasyPrint later
          sudo apt-get install -y libgomp1 libcairo2 pango1.0-tools fonts-dejavu-core

      - name: Pin pip tooling to constraints
        working-directory: packages
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
          PIP_PREFER_BINARY: "1"
        run: |
          pip install -r constraints/tooling-${{ runner.os }}-py${{ matrix.python-version }}.txt

      - name: Install project with constraints
        working-directory: packages
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
          PIP_PREFER_BINARY: "1"
        run: |
          pip install -e ".[all]" -c constraints/constraints-${{ runner.os }}-py${{ matrix.python-version }}.txt
          pip check
          python -c "import numpy,scipy,pandas,sklearn; print('OK wheels:', numpy.__version__, scipy.__version__, pandas.__version__, sklearn.__version__)"

      - name: Enforce wheel-only for heavy deps
        working-directory: packages
        run: |
          pip install --only-binary=:all: \
            numpy scipy pandas scikit-learn shap xgboost lightgbm matplotlib seaborn \
            -c constraints/constraints-${{ runner.os }}-py${{ matrix.python-version }}.txt

      - name: Runtime smoke
        working-directory: packages
        run: |
          python - <<'PY'
          import xgboost, lightgbm, shap
          import numpy as np, pandas as pd
          print("xgboost:", xgboost.__version__)
          print("lightgbm:", lightgbm.__version__)
          print("shap:", shap.__version__)
          PY

      - name: Diagnose wheel vs source builds
        working-directory: packages
        run: |
          python diagnose_wheels.py

      # Optional: Enable packaging assertion in CI
      - name: Verify packaging
        run: |
          GLASSALPHA_ASSERT_PACKAGING=1 python -c "import glassalpha.report"
        working-directory: packages

      # Optional: Validate coverage gates locally (for development)
      - name: Validate Coverage Gates (optional)
        run: |
          python test_coverage_gates.py
        working-directory: packages
        continue-on-error: true

      # Fast logging contract guard (before tests)
      - name: Enforce single-arg logging
        run: |
          python - <<'PY'
          import ast, sys, pathlib
          bad = []
          root = pathlib.Path("src/glassalpha")
          for p in root.rglob("*.py"):
              tree = ast.parse(p.read_text(encoding="utf-8"))
              for node in ast.walk(tree):
                  if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute):
                      if node.func.attr in {"debug","info","warning","error","critical","exception"}:
                          # More than one positional arg means printf-style or extra args
                          if len(node.args) > 1:
                              bad.append(f"{p}:{node.lineno}")
          if bad:
              print("printf-style logging detected (multiple positional args):")
              print("\n".join(bad))
              sys.exit(1)
          PY
        working-directory: packages

      # Fast import contract guard (prevent eager imports of heavy deps)
      - name: Enforce lazy imports for heavy dependencies
        run: |
          python - <<'PY'
          import ast, sys, pathlib
          bad = []
          root = pathlib.Path("src/glassalpha")

          # Heavy dependencies that should only be imported lazily
          heavy_deps = {"xgboost", "lightgbm", "shap"}

          for p in root.rglob("*.py"):
              tree = ast.parse(p.read_text(encoding="utf-8"))
              for node in ast.walk(tree):
                  if isinstance(node, ast.Import):
                      for alias in node.names:
                          if alias.name.split('.')[0] in heavy_deps:
                              bad.append(f"{p}:{node.lineno} - Eager import of {alias.name}")
                  elif isinstance(node, ast.ImportFrom):
                      if node.module and node.module.split('.')[0] in heavy_deps:
                          bad.append(f"{p}:{node.lineno} - Eager import of {node.module}")

          if bad:
              print("Eager imports of heavy dependencies detected (use lazy imports instead):")
              print("\n".join(bad))
              sys.exit(1)
          PY
        working-directory: packages

      # Run tests with coverage collection
      - name: Run tests with coverage
        run: |
          # Install test dependencies
          pip install numpy pandas scikit-learn pyyaml

          # Run contract guard tests (fast feedback)
          echo "Running contract guard tests..."
          pytest -xvs tests/contracts/ --cov=src --cov-report=term-missing

          # Run core functionality tests (works with any dependency level)
          echo "Running core functionality tests..."
          pytest -q tests/test_core_foundation.py tests/test_cli_basic.py tests/test_config_loading.py tests/test_plugin_dependencies.py --cov=src --cov-report=term-missing --cov-append

          # Run model tests (depends on dependency level)
          if [ "${{ matrix.dependencies }}" = "core" ]; then
            echo "Running core model tests (LogisticRegression only)..."
            pytest -q tests/test_model_integration.py -k "logistic" --cov=src --cov-report=term-missing --cov-append
          else
            echo "Running full model tests (all models available)..."
            pytest -q tests/test_model_integration.py tests/test_xgboost_basic.py --cov=src --cov-report=term-missing --cov-append
          fi

          # Run hot spot tests with coverage
          echo "Running hot spot tests with coverage..."
          pytest -q tests/test_pipeline_basic.py::test_pipeline_logs_initialization tests/test_end_to_end.py::test_multiple_model_types tests/test_model_integration.py::test_model_saving_and_loading --cov=src --cov-report=term-missing --cov-append

          # Run full test suite with coverage (skip if core-only)
          if [ "${{ matrix.dependencies }}" = "full" ]; then
            echo "Running full test suite with coverage..."
            pytest -q --cov=src --cov-report=term-missing
          fi
        working-directory: packages

      # Coverage Gates
      - name: Coverage Gates
        run: |
          # Combine coverage data from all test runs (handle single file case)
          echo "Combining coverage data..."
          if coverage combine 2>/dev/null; then
            echo "Coverage data combined successfully"
          else
            echo "Single coverage file or no data to combine"
          fi

          echo '--- Gate 1: Critical-path modules (90%+) ---'
          coverage report --precision=2 \
            --include="src/glassalpha/config/*,src/glassalpha/models/*,src/glassalpha/pipeline/*,src/glassalpha/report/renderer.py,src/glassalpha/metrics/core.py,src/glassalpha/metrics/thresholds.py,src/glassalpha/core/interfaces.py,src/glassalpha/core/registry.py" \
            --fail-under=90

          echo -e '\n--- Gate 2: Full repository (70% trend-only) ---'
          coverage report --precision=2 --fail-under=0
          coverage xml

          # Run trend checking script
          mkdir -p .ci
          python .ci/coverage_gate.py
        working-directory: packages

      # Upload coverage baseline for next run (only on success)
      - name: Upload coverage baseline
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-baseline
          path: packages/.ci/coverage-baseline.json
          retention-days: 30
