name: Dataset Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run weekly to catch upstream dataset changes
    - cron: "0 0 * * 0"

permissions:
  contents: read

jobs:
    test-dataset-offline:
    name: Test Dataset Fetching (Offline Mode)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Test offline mode behavior
        run: pytest tests/ci/test_dataset_offline.py -v

    test-dataset-online:
    name: Test Dataset Fetching (Online Mode)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Test online dataset fetching
        run: pytest tests/ci/test_dataset_online.py -v

    test-dataset-concurrency:
    name: Test Concurrent Dataset Fetching
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Test concurrent fetching safety
        run: pytest tests/ci/test_dataset_concurrent.py -v

    test-dataset-cli:
    name: Test Dataset CLI Commands
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Test CLI dataset commands
        run: pytest tests/ci/test_dataset_cli.py -v
